analyzer:

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    always_use_package_imports: true
    prefer_const_constructors: true
    prefer_final_fields: true
    sort_constructors_first: true
    unnecessary_null_checks: true
    use_super_parameters: true
    prefer_expression_function_bodies: true
